In [5]:
# Demonstrates column vectors

import numpy as np
from qiskit import __version__

print(__version__)

# Qubit state vectors
ket0 = np.array([[1], [0]])
ket1 = np.array([[0], [1]])

# Calculate average
print(ket0 / 2 + ket1 / 2)

2.4.0
[[0.5]
 [0.5]]


In [7]:
# Demonstrates matrices

M1 = np.array([[1, 1], [0, 0]])
M2 = np.array([[1, 0], [0, 1]])
M = M1 / 2 + M2 / 2
print(M1)

[[1 1]
 [0 0]]


In [8]:
# Matrix multiplication
print(np.matmul(M1, ket1))
print(np.matmul(M1, M2))
print(np.matmul(M, M))


[[1]
 [0]]
[[1 1]
 [0 0]]
[[1.   0.75]
 [0.   0.25]]
