In [4]:
# Operate on probability vectors

import numpy as np
from qiskit.visualization import array_to_latex
from qiskit import __version__

print(f"Qiskit Version: {__version__}")

# Qubit state vectors
ket0 = np.array([[1], [0]])
ket1 = np.array([[0], [1]])

# Calculate average
print("Average: ")
display(array_to_latex(ket0 / 2 + ket1 / 2))

Qiskit Version: 2.4.0
Average: 


<IPython.core.display.Latex object>

In [5]:
# Demonstrates matrix operations

M1 = np.array([[1, 1], [0, 0]])
M2 = np.array([[1, 0], [0, 1]])
M = M1 / 2 + M2 / 2
print("M1 / 2 + M2 / 2 =")
print()
display(array_to_latex(M))

M1 / 2 + M2 / 2 =



<IPython.core.display.Latex object>

In [7]:
# Demonstrates matrix multiplication

print("M1 * ket1 =")
print()
display(array_to_latex(np.matmul(M1, ket1)))
print()
print("M1 * M2 =")
print()
print(np.matmul(M1, M2))
display(array_to_latex(np.matmul(M1, M2)))
print()
print("M * M =")
print()
print(np.matmul(M, M))
np.matmul(M1, M2)


M1 * ket1 =

[[1]
 [0]]


<IPython.core.display.Latex object>


M1 * M2 =

[[1 1]
 [0 0]]

M * M =

[[1.   0.75]
 [0.   0.25]]
